# Generated by Django 4.1.2 on 2023-05-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0003_alter_recipe_ingredients_alter_recipe_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('unit', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
