# Generated by Django 4.1.2 on 2023-04-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_shoppinglist_quantity_shoppinglist_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='unit',
        ),
    ]
