# Generated by Django 4.1.2 on 2022-10-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_alter_shoppinglist_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='user_name',
            new_name='user',
        ),
    ]
