# Generated by Django 4.1.2 on 2022-10-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('recipes', '0002_rename_name_recipe_recipe_name'),
        ('meal_planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meal_Plan',
            new_name='MealPlan',
        ),
        migrations.RenameField(
            model_name='mealplan',
            old_name='name',
            new_name='recipe_name',
        ),
    ]
