# Generated by Django 4.1.2 on 2023-05-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='meal_type',
        ),
    ]
