# Generated by Django 4.1.2 on 2022-10-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('time', models.CharField(max_length=255)),
                ('servings', models.IntegerField()),
                ('image', models.CharField(max_length=2048)),
            ],
        ),
    ]
