# Generated by Django 4.1.2 on 2022-10-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.TextField(max_length=2048),
        ),
    ]
