# Generated by Django 4.1.2 on 2023-02-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_ingredients_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite_toggle',
            field=models.BooleanField(null=True),
        ),
    ]
